services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sidtra-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  backend-api:
    build: .
    container_name: sidtra-backend-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq